export default [
  {
    id: "123",
    name: "White T-Shirt",
    brand: "Nike",
    category: "Shirts",
    price: "10.00",
    description: "Easy choice but outstanding look!",
    pic: require("images/cuadrante6.jpg"),
  },
  {
    id: "124",
    name: "Black Trousers",
    brand: "Adidas",
    category: "Trousers",
    price: "20.00",
    description: "Just look at them!",
    pic: require("images/cuadrante2.jpg"),
  },
  {
    id: "125",
    name: "Jean Jacket",
    brand: "Christian Dior",
    category: "Jacket",
    price: "15.00",
    description: "This jacket will make you look like Michael!",
    pic: require("images/cuadrante1.jpg"),
  },
  {
    id: "126",
    name: "Black Socks",
    brand: "Nike",
    category: "Socks",
    price: "3.00",
    description: "Perfect for those who  suffer of cold nights!",
    pic: require("images/cuadrante5.jpg"),
  },
  {
    id: "127",
    name: "Training Joggers",
    brand: "Puma",
    category: "Trousers",
    price: "30.00",
    description: "Most amazing joggers in tha world!",
    pic: require("images/cuadrante4.jpg"),
  },
  {
    id: "128",
    name: "Spurs Shirt",
    brand: "Nike",
    category: "Shirts",
    price: "35.00",
    description: "Be Manu Ginobilli for a day!",
    pic: require("images/cuadrante7.jpg"),
  },
];
